# Site settings
title: Dzjon Hessing
email: dhessing@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dzjon.nl" # the base hostname & protocol for your site
# twitter_username: dzjonhessing
github_username:  dhessing
telegram_username: dhessing
permalink: '/:year/:month/:day/:title/'
ga_analytics: UA-33653650-1
paginate: 5
paginate_path: "/page/:num/"

udacity-timestamp: 2016-04-04

udacity:
  introduction_to_statistics: 100
  linear_algebra_refresher_course: 73

assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

jekyll-archives:
  enabled:
    - tags
    - categories
    - month
  layouts:
    month: month-archive
    tag: archive
    category: archive

gems:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-timeago